name: Nuget deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: add feed
      run: dotnet nuget add source https://nuget.pkg.github.com/acceliox/index.json --name github --store-password-in-clear-text --username acceliox --password ${{ secrets.VA_NUGET_FEED_TOKEN }}
    - name: Pack
      run: dotnet pack --configuration Release *.sln --output ./
    - name: PushGithub
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/acceliox/index.json --skip-duplicate
        